/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
   
    public static void main(String[] args) 
    {
        System.out.println("Starting QCalc..");
        //StandardCalculator calc = new StandardCalculator();
        //calc.subtract(Double.MAX_VALUE, 1.0);
        //System.out.println(calc.getResult());
        LogicCalculator calc = new LogicCalculator();
        calc.AND(8, 6);
        calc.printResult();



    }

    public Object getGreeting() {
        return new App();
    }
}
